export const HUE_RED = 0.000;
export const HUE_CHERRY = 2.656;
export const HUE_SCARLET = 5.313;
export const HUE_GRAPEFRUIT = 7.969;
export const HUE_VERMILION = 10.625;
export const HUE_CLEMENTINE = 13.281;
export const HUE_BLAZE_ORANGE = 15.938;
export const HUE_ORANGE_PUMPKIN = 18.594;
export const HUE_ORANGE = 21.250;
export const HUE_TANGOR = 23.906;
export const HUE_GOLDEN_POPPY = 26.563;
export const HUE_GOLDENROD = 29.219;
export const HUE_AMBER = 31.875;
export const HUE_GOLD = 34.531;
export const HUE_BROOM = 37.188;
export const HUE_CANTALOUPE = 39.844;
export const HUE_YELLOW = 42.500;
export const HUE_LEMON_LIME = 45.156;
export const HUE_BITTER_LEMON = 47.813;
export const HUE_HONEYDEW = 50.469;
export const HUE_LIME = 53.125;
export const HUE_SPRING_LIME = 55.781;
export const HUE_GREEN_GRAPE = 58.438;
export const HUE_FLORA = 61.094;
export const HUE_CHARTREUSE = 63.750;
export const HUE_CHARTREUSE_LAWN = 66.406;
export const HUE_LIMEADE = 69.063;
export const HUE_HARLEQUIN_LAWN = 71.719;
export const HUE_HARLEQUIN = 74.375;
export const HUE_HARLEQUIN_APPLE = 77.031;
export const HUE_SCREAMING_GREEN = 79.688;
export const HUE_GREENER_APPLE = 82.344;
export const HUE_GREEN = 85.000;
export const HUE_GREEN_MALACHITE = 87.656;
export const HUE_FREE_SPEECH_GREEN = 90.313;
export const HUE_IRISH_MALACHITE = 92.969;
export const HUE_IRISH_GREEN = 95.625;
export const HUE_IRISH_LUCK = 98.281;
export const HUE_IRISH_SPRING_GREEN = 100.938;
export const HUE_IRISH_EMERALD_GLEAM = 103.594;
export const HUE_NEW_SPRING_GREEN = 106.250;
export const HUE_SEA_SPRING = 108.906;
export const HUE_SPRING_AQUAMARINE = 111.563;
export const HUE_AQUAMARINE_SEA_FOAM = 114.219;
export const HUE_AQUAMARINE = 116.875;
export const HUE_AQUAMARINE_AQUA = 119.531;
export const HUE_BRIGHT_TURQUOISE = 122.188;
export const HUE_AQUA_CYAN = 124.844;
export const HUE_CYAN = 127.500;
export const HUE_CYAN_TURQUOISE = 130.156;
export const HUE_CYANISH_CAPRI = 132.813;
export const HUE_SKY = 135.469;
export const HUE_CAPRI = 138.125;
export const HUE_CELESTIAL_CAPRI = 140.781;
export const HUE_CORNFLOWER = 143.438;
export const HUE_CELESTIAL_AZURE = 146.094;
export const HUE_AZURE = 148.750;
export const HUE_AZURE_DENIM = 151.406;
export const HUE_BLUE_RIBBON = 154.063;
export const HUE_CERULEAN_DENIM = 156.719;
export const HUE_CERULEAN = 159.375;
export const HUE_PERSIAN_CERULEAN = 162.031;
export const HUE_BLUISH_CERULEAN = 164.688;
export const HUE_BLUER_PERSIAN_BLUE = 167.344;
export const HUE_BLUE = 170.000;
export const HUE_BLUER_BERRY = 172.656;
export const HUE_BLUISH_ULTRAMARINE = 175.313;
export const HUE_OCEAN = 177.969;
export const HUE_ULTRAMARINE = 180.625;
export const HUE_ULTRAMARINE_ORCHID = 183.281;
export const HUE_ELECTRIC_VIOLET = 185.938;
export const HUE_VIOLET_ORCHID = 188.594;
export const HUE_VIOLET = 191.250;
export const HUE_PLUM = 193.906;
export const HUE_GRAPE = 196.563;
export const HUE_ENERGETIC_PURPLE = 199.219;
export const HUE_PURPLE = 201.875;
export const HUE_FAR_OUT_PURPLE = 204.531;
export const HUE_PSYCHEDELIC_PURPLE = 207.188;
export const HUE_CARNATION = 209.844;
export const HUE_MAGENTA = 212.500;
export const HUE_WARM_MAGENTA = 215.156;
export const HUE_HOT_MAGENTA = 217.813;
export const HUE_HOT_MAGENTA_CERISE = 220.469;
export const HUE_CERISE = 223.125;
export const HUE_BEVERLY_HILLS_CERISE = 225.781;
export const HUE_HOLLYWOOD_CERISE = 228.438;
export const HUE_HOLLYWOOD_ROSE = 231.094;
export const HUE_ROSE = 233.750;
export const HUE_STRAWBERRY_ROSE = 236.406;
export const HUE_RAZZMATAZZ = 239.063;
export const HUE_POMEGRANATE = 241.719;
export const HUE_CRIMSON = 244.375;
export const HUE_CRIMSON_TORCH = 247.031;
export const HUE_TORCH_RED = 249.688;
export const HUE_REDDER_TORCH_RED = 252.344;

export const HUEMAP = {
    "HUE_RED": HUE_RED,
    "HUE_CHERRY": HUE_CHERRY,
    "HUE_SCARLET": HUE_SCARLET,
    "HUE_GRAPEFRUIT": HUE_GRAPEFRUIT,
    "HUE_VERMILION": HUE_VERMILION,
    "HUE_CLEMENTINE": HUE_CLEMENTINE,
    "HUE_BLAZE_ORANGE": HUE_BLAZE_ORANGE,
    "HUE_ORANGE_PUMPKIN": HUE_ORANGE_PUMPKIN,
    "HUE_ORANGE": HUE_ORANGE,
    "HUE_TANGOR": HUE_TANGOR,
    "HUE_GOLDEN_POPPY": HUE_GOLDEN_POPPY,
    "HUE_GOLDENROD": HUE_GOLDENROD,
    "HUE_AMBER": HUE_AMBER,
    "HUE_GOLD": HUE_GOLD,
    "HUE_BROOM": HUE_BROOM,
    "HUE_CANTALOUPE": HUE_CANTALOUPE,
    "HUE_YELLOW": HUE_YELLOW,
    "HUE_LEMON_LIME": HUE_LEMON_LIME,
    "HUE_BITTER_LEMON": HUE_BITTER_LEMON,
    "HUE_HONEYDEW": HUE_HONEYDEW,
    "HUE_LIME": HUE_LIME,
    "HUE_SPRING_LIME": HUE_SPRING_LIME,
    "HUE_GREEN_GRAPE": HUE_GREEN_GRAPE,
    "HUE_FLORA": HUE_FLORA,
    "HUE_CHARTREUSE": HUE_CHARTREUSE,
    "HUE_CHARTREUSE_LAWN": HUE_CHARTREUSE_LAWN,
    "HUE_LIMEADE": HUE_LIMEADE,
    "HUE_HARLEQUIN_LAWN": HUE_HARLEQUIN_LAWN,
    "HUE_HARLEQUIN": HUE_HARLEQUIN,
    "HUE_HARLEQUIN_APPLE": HUE_HARLEQUIN_APPLE,
    "HUE_SCREAMING_GREEN": HUE_SCREAMING_GREEN,
    "HUE_GREENER_APPLE": HUE_GREENER_APPLE,
    "HUE_GREEN": HUE_GREEN,
    "HUE_GREEN_MALACHITE": HUE_GREEN_MALACHITE,
    "HUE_FREE_SPEECH_GREEN": HUE_FREE_SPEECH_GREEN,
    "HUE_IRISH_MALACHITE": HUE_IRISH_MALACHITE,
    "HUE_IRISH_GREEN": HUE_IRISH_GREEN,
    "HUE_IRISH_LUCK": HUE_IRISH_LUCK,
    "HUE_IRISH_SPRING_GREEN": HUE_IRISH_SPRING_GREEN,
    "HUE_IRISH_EMERALD_GLEAM": HUE_IRISH_EMERALD_GLEAM,
    "HUE_NEW_SPRING_GREEN": HUE_NEW_SPRING_GREEN,
    "HUE_SEA_SPRING": HUE_SEA_SPRING,
    "HUE_SPRING_AQUAMARINE": HUE_SPRING_AQUAMARINE,
    "HUE_AQUAMARINE_SEA_FOAM": HUE_AQUAMARINE_SEA_FOAM,
    "HUE_AQUAMARINE": HUE_AQUAMARINE,
    "HUE_AQUAMARINE_AQUA": HUE_AQUAMARINE_AQUA,
    "HUE_BRIGHT_TURQUOISE": HUE_BRIGHT_TURQUOISE,
    "HUE_AQUA_CYAN": HUE_AQUA_CYAN,
    "HUE_CYAN": HUE_CYAN,
    "HUE_CYAN_TURQUOISE": HUE_CYAN_TURQUOISE,
    "HUE_CYANISH_CAPRI": HUE_CYANISH_CAPRI,
    "HUE_SKY": HUE_SKY,
    "HUE_CAPRI": HUE_CAPRI,
    "HUE_CELESTIAL_CAPRI": HUE_CELESTIAL_CAPRI,
    "HUE_CORNFLOWER": HUE_CORNFLOWER,
    "HUE_CELESTIAL_AZURE": HUE_CELESTIAL_AZURE,
    "HUE_AZURE": HUE_AZURE,
    "HUE_AZURE_DENIM": HUE_AZURE_DENIM,
    "HUE_BLUE_RIBBON": HUE_BLUE_RIBBON,
    "HUE_CERULEAN_DENIM": HUE_CERULEAN_DENIM,
    "HUE_CERULEAN": HUE_CERULEAN,
    "HUE_PERSIAN_CERULEAN": HUE_PERSIAN_CERULEAN,
    "HUE_BLUISH_CERULEAN": HUE_BLUISH_CERULEAN,
    "HUE_BLUER_PERSIAN_BLUE": HUE_BLUER_PERSIAN_BLUE,
    "HUE_BLUE": HUE_BLUE,
    "HUE_BLUER_BERRY": HUE_BLUER_BERRY,
    "HUE_BLUISH_ULTRAMARINE": HUE_BLUISH_ULTRAMARINE,
    "HUE_OCEAN": HUE_OCEAN,
    "HUE_ULTRAMARINE": HUE_ULTRAMARINE,
    "HUE_ULTRAMARINE_ORCHID": HUE_ULTRAMARINE_ORCHID,
    "HUE_ELECTRIC_VIOLET": HUE_ELECTRIC_VIOLET,
    "HUE_VIOLET_ORCHID": HUE_VIOLET_ORCHID,
    "HUE_VIOLET": HUE_VIOLET,
    "HUE_PLUM": HUE_PLUM,
    "HUE_GRAPE": HUE_GRAPE,
    "HUE_ENERGETIC_PURPLE": HUE_ENERGETIC_PURPLE,
    "HUE_PURPLE": HUE_PURPLE,
    "HUE_FAR_OUT_PURPLE": HUE_FAR_OUT_PURPLE,
    "HUE_PSYCHEDELIC_PURPLE": HUE_PSYCHEDELIC_PURPLE,
    "HUE_CARNATION": HUE_CARNATION,
    "HUE_MAGENTA": HUE_MAGENTA,
    "HUE_WARM_MAGENTA": HUE_WARM_MAGENTA,
    "HUE_HOT_MAGENTA": HUE_HOT_MAGENTA,
    "HUE_HOT_MAGENTA_CERISE": HUE_HOT_MAGENTA_CERISE,
    "HUE_CERISE": HUE_CERISE,
    "HUE_BEVERLY_HILLS_CERISE": HUE_BEVERLY_HILLS_CERISE,
    "HUE_HOLLYWOOD_CERISE": HUE_HOLLYWOOD_CERISE,
    "HUE_HOLLYWOOD_ROSE": HUE_HOLLYWOOD_ROSE,
    "HUE_ROSE": HUE_ROSE,
    "HUE_STRAWBERRY_ROSE": HUE_STRAWBERRY_ROSE,
    "HUE_RAZZMATAZZ": HUE_RAZZMATAZZ,
    "HUE_POMEGRANATE": HUE_POMEGRANATE,
    "HUE_CRIMSON": HUE_CRIMSON,
    "HUE_CRIMSON_TORCH": HUE_CRIMSON_TORCH,
    "HUE_TORCH_RED": HUE_TORCH_RED,
    "HUE_REDDER_TORCH_RED": HUE_REDDER_TORCH_RED,
}