// https://bitfume.com/tools/hue-names/#x
export const HUE_RED=0.00;
export const HUE_CHERRY=3.75;
export const HUE_SCARLET=7.50;
export const HUE_GRAPEFRUIT=11.25;
export const HUE_VERMILION=15.00;
export const HUE_CLEMENTINE=18.75;
export const HUE_BLAZE_ORANGE=22.50;
export const HUE_ORANGE_PUMPKIN=26.25;
export const HUE_ORANGE=30.00;
export const HUE_TANGOR=33.75;
export const HUE_GOLDEN_POPPY=37.50;
export const HUE_GOLDENROD=41.25;
export const HUE_AMBER=45.00;
export const HUE_GOLD=48.75;
export const HUE_BROOM=52.50;
export const HUE_CANTALOUPE=56.25;
export const HUE_YELLOW=60.00;
export const HUE_LEMON_LIME=63.75;
export const HUE_BITTER_LEMON=67.50;
export const HUE_HONEYDEW=71.25;
export const HUE_LIME=75.00;
export const HUE_SPRING_LIME=78.75;
export const HUE_GREEN_GRAPE=82.50;
export const HUE_FLORA=86.25;
export const HUE_CHARTREUSE=90.00;
export const HUE_CHARTREUSE_LAWN=93.75;
export const HUE_LIMEADE=97.50;
export const HUE_HARLEQUIN_LAWN=101.25;
export const HUE_HARLEQUIN=105.00;
export const HUE_HARLEQUIN_APPLE=108.75;
export const HUE_SCREAMING_GREEN=112.50;
export const HUE_GREENER_APPLE=116.25;
export const HUE_GREEN=120.00;
export const HUE_GREEN_MALACHITE=123.75;
export const HUE_FREE_SPEECH_GREEN=127.50;
export const HUE_IRISH_MALACHITE=131.25;
export const HUE_IRISH_GREEN=135.00;
export const HUE_IRISH_LUCK=138.75;
export const HUE_IRISH_SPRING_GREEN=142.50;
export const HUE_IRISH_EMERALD_GLEAM=146.25;
export const HUE_NEW_SPRING_GREEN=150.00;
export const HUE_SEA_SPRING=153.75;
export const HUE_SPRING_AQUAMARINE=157.50;
export const HUE_AQUAMARINE_SEA_FOAM=161.25;
export const HUE_AQUAMARINE=165.00;
export const HUE_AQUAMARINE_AQUA=168.75;
export const HUE_BRIGHT_TURQUOISE=172.50;
export const HUE_AQUA_CYAN=176.25;
export const HUE_CYAN=180.00;
export const HUE_CYAN_TURQUOISE=183.75;
export const HUE_CYANISH_CAPRI=187.50;
export const HUE_SKY=191.25;
export const HUE_CAPRI=195.00;
export const HUE_CELESTIAL_CAPRI=198.75;
export const HUE_CORNFLOWER=202.50;
export const HUE_CELESTIAL_AZURE=206.25;
export const HUE_AZURE=210.00;
export const HUE_AZURE_DENIM=213.75;
export const HUE_BLUE_RIBBON=217.50;
export const HUE_CERULEAN_DENIM=221.25;
export const HUE_CERULEAN=225.00;
export const HUE_PERSIAN_CERULEAN=228.75;
export const HUE_BLUISH_CERULEAN=232.50;
export const HUE_BLUER_PERSIAN_BLUE=236.25;
export const HUE_BLUE=240.00;
export const HUE_BLUER_BERRY=243.75;
export const HUE_BLUISH_ULTRAMARINE=247.50;
export const HUE_OCEAN=251.25;
export const HUE_ULTRAMARINE=255.00;
export const HUE_ULTRAMARINE_ORCHID=258.75;
export const HUE_ELECTRIC_VIOLET=262.50;
export const HUE_VIOLET_ORCHID=266.25;
export const HUE_VIOLET=270.00;
export const HUE_PLUM=273.75;
export const HUE_GRAPE=277.50;
export const HUE_ENERGETIC_PURPLE=281.25;
export const HUE_PURPLE=285.00;
export const HUE_FAR_OUT_PURPLE=288.75;
export const HUE_PSYCHEDELIC_PURPLE=292.50;
export const HUE_CARNATION=296.25;
export const HUE_MAGENTA=300.00;
export const HUE_WARM_MAGENTA=303.75;
export const HUE_HOT_MAGENTA=307.50;
export const HUE_HOT_MAGENTA_CERISE=311.25;
export const HUE_CERISE=315.00;
export const HUE_BEVERLY_HILLS_CERISE=318.75;
export const HUE_HOLLYWOOD_CERISE=322.50;
export const HUE_HOLLYWOOD_ROSE=326.25;
export const HUE_ROSE=330.00;
export const HUE_STRAWBERRY_ROSE=333.75;
export const HUE_RAZZMATAZZ=337.50;
export const HUE_POMEGRANATE=341.25;
export const HUE_CRIMSON=345.00;
export const HUE_CRIMSON_TORCH=348.75;
export const HUE_TORCH_RED=352.50;
export const HUE_REDDER_TORCH_RED=356.25;

export const HUEMAP = {
    "HUE_RED": HUE_RED,
    "HUE_CHERRY": HUE_CHERRY,
    "HUE_SCARLET": HUE_SCARLET,
    "HUE_GRAPEFRUIT": HUE_GRAPEFRUIT,
    "HUE_VERMILION": HUE_VERMILION,
    "HUE_CLEMENTINE": HUE_CLEMENTINE,
    "HUE_BLAZE_ORANGE": HUE_BLAZE_ORANGE,
    "HUE_ORANGE_PUMPKIN": HUE_ORANGE_PUMPKIN,
    "HUE_ORANGE": HUE_ORANGE,
    "HUE_TANGOR": HUE_TANGOR,
    "HUE_GOLDEN_POPPY": HUE_GOLDEN_POPPY,
    "HUE_GOLDENROD": HUE_GOLDENROD,
    "HUE_AMBER": HUE_AMBER,
    "HUE_GOLD": HUE_GOLD,
    "HUE_BROOM": HUE_BROOM,
    "HUE_CANTALOUPE": HUE_CANTALOUPE,
    "HUE_YELLOW": HUE_YELLOW,
    "HUE_LEMON_LIME": HUE_LEMON_LIME,
    "HUE_BITTER_LEMON": HUE_BITTER_LEMON,
    "HUE_HONEYDEW": HUE_HONEYDEW,
    "HUE_LIME": HUE_LIME,
    "HUE_SPRING_LIME": HUE_SPRING_LIME,
    "HUE_GREEN_GRAPE": HUE_GREEN_GRAPE,
    "HUE_FLORA": HUE_FLORA,
    "HUE_CHARTREUSE": HUE_CHARTREUSE,
    "HUE_CHARTREUSE_LAWN": HUE_CHARTREUSE_LAWN,
    "HUE_LIMEADE": HUE_LIMEADE,
    "HUE_HARLEQUIN_LAWN": HUE_HARLEQUIN_LAWN,
    "HUE_HARLEQUIN": HUE_HARLEQUIN,
    "HUE_HARLEQUIN_APPLE": HUE_HARLEQUIN_APPLE,
    "HUE_SCREAMING_GREEN": HUE_SCREAMING_GREEN,
    "HUE_GREENER_APPLE": HUE_GREENER_APPLE,
    "HUE_GREEN": HUE_GREEN,
    "HUE_GREEN_MALACHITE": HUE_GREEN_MALACHITE,
    "HUE_FREE_SPEECH_GREEN": HUE_FREE_SPEECH_GREEN,
    "HUE_IRISH_MALACHITE": HUE_IRISH_MALACHITE,
    "HUE_IRISH_GREEN": HUE_IRISH_GREEN,
    "HUE_IRISH_LUCK": HUE_IRISH_LUCK,
    "HUE_IRISH_SPRING_GREEN": HUE_IRISH_SPRING_GREEN,
    "HUE_IRISH_EMERALD_GLEAM": HUE_IRISH_EMERALD_GLEAM,
    "HUE_NEW_SPRING_GREEN": HUE_NEW_SPRING_GREEN,
    "HUE_SEA_SPRING": HUE_SEA_SPRING,
    "HUE_SPRING_AQUAMARINE": HUE_SPRING_AQUAMARINE,
    "HUE_AQUAMARINE_SEA_FOAM": HUE_AQUAMARINE_SEA_FOAM,
    "HUE_AQUAMARINE": HUE_AQUAMARINE,
    "HUE_AQUAMARINE_AQUA": HUE_AQUAMARINE_AQUA,
    "HUE_BRIGHT_TURQUOISE": HUE_BRIGHT_TURQUOISE,
    "HUE_AQUA_CYAN": HUE_AQUA_CYAN,
    "HUE_CYAN": HUE_CYAN,
    "HUE_CYAN_TURQUOISE": HUE_CYAN_TURQUOISE,
    "HUE_CYANISH_CAPRI": HUE_CYANISH_CAPRI,
    "HUE_SKY": HUE_SKY,
    "HUE_CAPRI": HUE_CAPRI,
    "HUE_CELESTIAL_CAPRI": HUE_CELESTIAL_CAPRI,
    "HUE_CORNFLOWER": HUE_CORNFLOWER,
    "HUE_CELESTIAL_AZURE": HUE_CELESTIAL_AZURE,
    "HUE_AZURE": HUE_AZURE,
    "HUE_AZURE_DENIM": HUE_AZURE_DENIM,
    "HUE_BLUE_RIBBON": HUE_BLUE_RIBBON,
    "HUE_CERULEAN_DENIM": HUE_CERULEAN_DENIM,
    "HUE_CERULEAN": HUE_CERULEAN,
    "HUE_PERSIAN_CERULEAN": HUE_PERSIAN_CERULEAN,
    "HUE_BLUISH_CERULEAN": HUE_BLUISH_CERULEAN,
    "HUE_BLUER_PERSIAN_BLUE": HUE_BLUER_PERSIAN_BLUE,
    "HUE_BLUE": HUE_BLUE,
    "HUE_BLUER_BERRY": HUE_BLUER_BERRY,
    "HUE_BLUISH_ULTRAMARINE": HUE_BLUISH_ULTRAMARINE,
    "HUE_OCEAN": HUE_OCEAN,
    "HUE_ULTRAMARINE": HUE_ULTRAMARINE,
    "HUE_ULTRAMARINE_ORCHID": HUE_ULTRAMARINE_ORCHID,
    "HUE_ELECTRIC_VIOLET": HUE_ELECTRIC_VIOLET,
    "HUE_VIOLET_ORCHID": HUE_VIOLET_ORCHID,
    "HUE_VIOLET": HUE_VIOLET,
    "HUE_PLUM": HUE_PLUM,
    "HUE_GRAPE": HUE_GRAPE,
    "HUE_ENERGETIC_PURPLE": HUE_ENERGETIC_PURPLE,
    "HUE_PURPLE": HUE_PURPLE,
    "HUE_FAR_OUT_PURPLE": HUE_FAR_OUT_PURPLE,
    "HUE_PSYCHEDELIC_PURPLE": HUE_PSYCHEDELIC_PURPLE,
    "HUE_CARNATION": HUE_CARNATION,
    "HUE_MAGENTA": HUE_MAGENTA,
    "HUE_WARM_MAGENTA": HUE_WARM_MAGENTA,
    "HUE_HOT_MAGENTA": HUE_HOT_MAGENTA,
    "HUE_HOT_MAGENTA_CERISE": HUE_HOT_MAGENTA_CERISE,
    "HUE_CERISE": HUE_CERISE,
    "HUE_BEVERLY_HILLS_CERISE": HUE_BEVERLY_HILLS_CERISE,
    "HUE_HOLLYWOOD_CERISE": HUE_HOLLYWOOD_CERISE,
    "HUE_HOLLYWOOD_ROSE": HUE_HOLLYWOOD_ROSE,
    "HUE_ROSE": HUE_ROSE,
    "HUE_STRAWBERRY_ROSE": HUE_STRAWBERRY_ROSE,
    "HUE_RAZZMATAZZ": HUE_RAZZMATAZZ,
    "HUE_POMEGRANATE": HUE_POMEGRANATE,
    "HUE_CRIMSON": HUE_CRIMSON,
    "HUE_CRIMSON_TORCH": HUE_CRIMSON_TORCH,
    "HUE_TORCH_RED": HUE_TORCH_RED,
    "HUE_REDDER_TORCH_RED": HUE_REDDER_TORCH_RED,
}